name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        scope: '@redux-ai'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.15.9
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Configure npm authentication
      run: |
        cat << EOF > .npmrc
        //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
        registry=https://registry.npmjs.org/
        always-auth=true
        @redux-ai:registry=https://registry.npmjs.org/
        EOF

    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Build packages first
      run: |
        pnpm run -r --filter="./packages/*" build
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Build and test all
      run: |
        pnpm build
        pnpm run -r lint
        pnpm run -r test
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@redux-ai'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Configure npm authentication
        run: |
          cat << EOF > .npmrc
          //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          registry=https://registry.npmjs.org/
          always-auth=true
          @redux-ai:registry=https://registry.npmjs.org/
          EOF

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build packages first
        run: |
          pnpm run -r --filter="./packages/*" build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version and publish packages
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: pnpm changeset publish
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}